[package]
name = "tk-cron-trg-worker"
version = "0.3.0"
authors = ["mea <mateus.amin@mea.services>"]
edition = "2018"

[dependencies]
minreq = { version = "2.3.1" }

[profile.release]
opt-level = "z" 
lto = "fat"
codegen-units = 1
panic = 'abort'